### ISSUE TITLE
🛠 Tooling: Find or create an action that fixes up PR titles

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [JoshuaKGoldberg/template-typescript-node-package#574]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues?q=is%3Aissue) and found none that matched my issue.

### Overview

(I'll fill this out after the stream!)

**Comment by Lehoczky** [comment]
Hey Josh 👋

I've been using [action-semantic-pull-request](https://github.com/amannn/action-semantic-pull-request) for this exact purpose for a while now, and I found it working pretty well. It cannot automatically change the PR title, but it has a pretty helpful error message, and can be used in combination with [sticky-pull-request-comment](https://github.com/marocchino/sticky-pull-request-comment) to post the error as a PR comment.

Do you think it would worth a try? I'm open to create a draft PR for it.

**Comment by JoshuaKGoldberg** [comment]
Heya! 👋 

This is interesting! I hadn't seen those two actions - love that so many folks are using them. This is great. Thanks for showing me them. 😄 

I'd love to see an example repo that uses the two of them together. Especially one that can show a PR with the comment. Do you have a reference handy, or could you make one?

Note that long-term I'm planning on making a [generalized "GitHub Linter"](https://www.joshuakgoldberg.com/blog/my-plans-for-2024/#standalone-github-linter) that could do this. But that's not blocking at all, we can get this in in the interim.

**Comment by Lehoczky** [comment]
Of course, there you go: https://github.com/Lehoczky/pipeline-practices/pull/24

I'm using the example from the semantic pr action's REAMDE:

```yml
name: "Semantic PR title"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: write

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        id: lint_pr_title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: marocchino/sticky-pull-request-comment@v2
        if: always() && (steps.lint_pr_title.outputs.error_message != null)
        with:
          header: pr-title-lint-error
          message: |
            Hey there and thank you for opening this pull request! 👋🏼

            We require pull request titles to follow the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) and it looks like your proposed title needs to be adjusted.

            Details:

            ```
            ${{ steps.lint_pr_title.outputs.error_message }}
            ```

      - if: ${{ steps.lint_pr_title.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: pr-title-lint-error
          delete: true
```

https://github.com/Lehoczky/pipeline-practices/blob/master/.github/workflows/semantic-pr-title.yml

And the best thing is, if I change the PR title to follow the conventions, the PR comment automatically vanishes.
